# Generated by Django 3.1.2 on 2020-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregistereduser',
            name='web_site',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
