# Generated by Django 3.1.2 on 2020-10-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201023_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='is_hide',
            field=models.BooleanField(default=False, verbose_name='Hide'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='social',
            name='icon_name',
            field=models.CharField(choices=[('ss-facebook', 'Facebook'), ('ss-twitter', 'Twitter'), ('ss-dribble', 'Dribble'), ('ss-behance', 'Behance'), ('ss-instagram', 'Instagram'), ('ss-pinterest', 'Pinterest'), ('ss-rss', 'RSS')], default='ss-facebook', max_length=20),
        ),
    ]
