# Generated by Django 3.1.2 on 2020-10-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201023_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='is_hide',
        ),
        migrations.AddField(
            model_name='social',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
            preserve_default=False,
        ),
    ]
